app = "knowledge-card-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

[mounts]
  source = "nginx_config"
  destination = "/etc/nginx/nginx.conf"
