services:
  - type: web
    name: cardnote-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true
    plan: free
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
