app = "cardnote-backend"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "python -m uvicorn main:app --host 0.0.0.0 --port 8000"

[deploy]
  release_command = "echo 'No migrations needed'"
